In [1]:
import numpy as np

In [3]:
from gf321_utils import bvh_utils

In [4]:
test_data = bvh_utils.BVHData()

In [6]:
test_data.bvhRead('neural_lbs_data/dog1_testSeq_skeleton.bvh')

Reading BVH File.. neural_lbs_data/dog1_testSeq_skeleton.bvh
Done


In [8]:
joints, names = test_data.getJointAngles(withNames=True)

['Root',
 'Spine01',
 'Spine02',
 'LeftShoulder',
 'LeftArm',
 'LeftForeArm',
 'LeftWrist',
 'LeftHand',
 'End Site',
 'RightShoulder',
 'RightArm',
 'RightForeArm',
 'RightWrist',
 'RightHand',
 'End Site',
 'Neck01',
 'Neck02',
 'Neck03',
 'Neck04',
 'Head',
 'End Site',
 'LeftEar',
 'End Site',
 'RightEar',
 'End Site',
 'LeftLeg',
 'LeftLowerLeg',
 'LeftAnkle',
 'LeftFoot',
 'End Site',
 'RightLeg',
 'RightLowerLeg',
 'RightAnkle',
 'RightFoot',
 'End Site',
 'TailBase',
 'Tail1',
 'Tail2',
 'Tail3',
 'Tail4',
 'Tail5',
 'Tail6',
 'End Site']

In [6]:
rot = test_data.getJointAngles(withPos=False)
both = test_data.getJointAngles()
pos = test_data.getJointAngles(withJoints=False)

In [7]:
rot[0][0]

array([[-0.96791416, -0.23959981,  0.0757239 ],
       [-0.22374604,  0.9589429 ,  0.17425907],
       [-0.11436734,  0.1517249 , -0.98178392]])

In [10]:
both[0][0]

array([[-9.67914161e-01, -2.39599808e-01,  7.57239049e-02,
        -1.64358000e+03],
       [-2.23746037e-01,  9.58942901e-01,  1.74259067e-01,
         5.76536000e+02],
       [-1.14367340e-01,  1.51724895e-01, -9.81783921e-01,
         3.28814000e+02]])

In [11]:
pos[0][0]

array([-1643.58 ,   576.536,   328.814])

In [8]:
one = np.zeros((3,3))
one[0]=[0,1,2]
one[1]=[1,2,3]
one[2]=[4,5,6]

In [9]:
one[:-1,:-1]

array([[0., 1.],
       [1., 2.]])